### PR TITLE
Chore: Sonar onboard

### PR DESCRIPTION
**Pull request by tomsfernandez**

### CODE REVIEW

**Comment by tomsfernandez** [comment]
!gate waiver add SonarQube

**Comment by tomsfernandez** [comment]
!gate waiver menu

**Comment by tomsfernandez** [comment]
!gate waiver add Sonar

**Comment by pope1838** [comment]
!gate waiver add Sonar

**Comment by nschejtman** [comment]
!gate waiver add Sonar

**Comment by eduardo-rubio** [comment]
!gate waiver add Sonar

**Pull request closed without merging**
